/**
 * Seed data mirroring src/shared/config/site.ts + messages/ru.
 * Used by bootstrap on first CMS start when collections are empty.
 */
const seed = {
  services: [
    {
      slug: "construction",
      icon: "crane",
      order: 1,
      title: "Общестроительные работы",
      description: "Строительство промышленных и гражданских объектов под ключ.",
      features: ["Земляные и бетонные работы", "Каркас и ограждающие конструкции", "Отделка и благоустройство"],
    },
    {
      slug: "reconstruction",
      icon: "rebuild",
      order: 2,
      title: "Реконструкция",
      description: "Модернизация и усиление существующих зданий и сооружений.",
      features: ["Обследование конструкций", "Усиление и замена узлов", "Минимизация простоя"],
    },
    {
      slug: "low-rise",
      icon: "home",
      order: 3,
      title: "Малоэтажное строительство",
      description: "Жилые и административные объекты малой этажности.",
      features: ["Фундаменты", "Стены и кровля", "Инженерные сети"],
    },
    {
      slug: "prefabricated",
      icon: "warehouse",
      order: 4,
      title: "Быстровозводимые здания",
      description: "Склады, ангары и модульные сооружения.",
      features: ["Металлокаркас", "Сэндвич-панели", "Короткие сроки"],
    },
    {
      slug: "general-construction",
      icon: "layers",
      order: 5,
      title: "Генподряд",
      description: "Комплексное управление строительством как генеральный подрядчик.",
      features: ["Планирование", "Субподряд", "Сдача объекта"],
    },
    {
      slug: "pipe-supply",
      icon: "pipe",
      order: 6,
      title: "Поставка труб и фитингов",
      description: "Трубы, отводы, фланцы и соединительные детали.",
      features: ["Трубы стальные", "Фитинги", "Логистика на объект"],
    },
    {
      slug: "materials-supply",
      icon: "box",
      order: 7,
      title: "Инертные материалы",
      description: "Песок, щебень и сыпучие материалы для стройплощадки.",
      features: ["Щебень", "Песок", "Доставка"],
    },
    {
      slug: "metal-supply",
      icon: "metal",
      order: 8,
      title: "Металлопрокат",
      description: "Листовой и сортовой прокат для строительства и монтажа.",
      features: ["Балка и швеллер", "Лист", "Арматура"],
    },
    {
      slug: "pipeline-welding",
      icon: "pipeline",
      order: 9,
      title: "Монтаж трубопроводов",
      description: "Сварка и монтаж технологических трубопроводов.",
      features: ["Сварка", "Испытания", "Документация"],
    },
    {
      slug: "tank-welding",
      icon: "tank",
      order: 10,
      title: "Резервуары",
      description: "Изготовление и монтаж резервуаров и ёмкостей.",
      features: ["Сборка", "Сварка", "Антикоррозия"],
    },
    {
      slug: "steel-welding",
      icon: "steel",
      order: 11,
      title: "Металлоконструкции",
      description: "Изготовление и монтаж несущих металлоконструкций.",
      features: ["Изготовление", "Монтаж", "Контроль качества"],
    },
    {
      slug: "design",
      icon: "draft",
      order: 12,
      title: "Проектирование",
      description: "Проектная документация и согласования.",
      features: ["РД и ПД", "Сметы", "Сопровождение"],
    },
    {
      slug: "maintenance",
      icon: "wrench",
      order: 13,
      title: "Техническое обслуживание",
      description: "Сервис и ремонт промышленных объектов.",
      features: ["Плановые работы", "Аварийный ремонт", "Контроль"],
    },
  ],
  projects: [
    {
      slug: "p1",
      title: "Металлоконструкции на площадке",
      category: "construction",
      span: "tall" as const,
      description: "Монтаж несущих конструкций.",
    },
    {
      slug: "p2",
      title: "Монтажные работы",
      category: "installation",
      span: "normal" as const,
      description: "Монтаж оборудования и сетей.",
    },
    {
      slug: "p3",
      title: "Быстровозводимый комплекс",
      category: "prefabricated",
      span: "wide" as const,
      description: "Каркас и сэндвич-панели.",
    },
    {
      slug: "p4",
      title: "Реконструкция объекта",
      category: "reconstruction",
      span: "normal" as const,
      description: "Усиление и обновление.",
    },
    {
      slug: "p5",
      title: "Строительство цеха",
      category: "construction",
      span: "tall" as const,
      description: "Общестроительные работы.",
    },
    {
      slug: "p6",
      title: "Трубопроводный участок",
      category: "installation",
      span: "normal" as const,
      description: "Сварка трубопроводов.",
    },
    {
      slug: "p7",
      title: "Генподряд на объекте",
      category: "construction",
      span: "normal" as const,
      description: "Комплексное строительство.",
    },
    {
      slug: "p8",
      title: "Сервисное обслуживание",
      category: "maintenance",
      span: "wide" as const,
      description: "Плановое ТО.",
    },
  ],
  partners: [
    { name: "АО «Эмбамунайгаз»", order: 1 },
    { name: "АО «Мангистаумунайгаз»", order: 2 },
    { name: "Западный филиал АО «Казтрансойл»", order: 3 },
    { name: "ТОО «У-А-С Сервис»", order: 4 },
    { name: "ТОО «NASAR Solutions»", order: 5 },
    { name: "ТОО «GREEN ATYRAU»", order: 6 },
    { name: "ТОО «SMART TRANS»", order: 7 },
    { name: "ТОО «SUPRA OIL MARKET»", order: 8 },
    { name: "ТОО «CASPIAN CONTRACTORS TRUST»", order: 9 },
    { name: "ТОО «Кендирли Курылыс»", order: 10 },
    { name: "ТОО «ATYRAU PIPELINE SERVICE»", order: 11 },
    { name: "ТОО «Атыраумунайгазгеология-Сервис»", order: 12 },
    { name: "ТОО «Камистройсервис»", order: 13 },
  ],
  certificates: [
    { code: "ISO 9001", title: "Система менеджмента качества" },
    { code: "ISO 14001", title: "Экологический менеджмент" },
    { code: "OHSAS 18001", title: "Охрана труда и промышленная безопасность" },
    { code: "ГСЛ №0002796", title: "Государственная лицензия на строительно-монтажные работы" },
  ],
  vacancies: [
    {
      title: "Сварщик НАКС",
      active: true,
      contact: "7779405@mail.ru",
      requirements: ["Опыт от 3 лет", "Удостоверение НАКС", "Готовность к вахте"],
    },
  ],
};

export default seed;
